### ISSUE TITLE
Issues with URLs. Need https://www.wunderground.com/ in place of http://www.wunderground.com/

### ISSUE THREAD

**Issue by LaurentGentzbittel** [Ram-N/weatherData#28]
Dear author,
I had to manually hack the code of createWU_Custom_URL() to fix the issue on my Linux system.
Might it be fixed into the git repository ?

Thank you for your great work taht is most useful !

**Comment by Ram-N** [comment]
Hi Laurent,

Thank you for the note. The git repository is indeed ahead and has a few URL related fixes.
However, if you can share whatever you have done (and explain it), we could consider merging it into the code.

Can you post here what your issue was, and what you changed in createWU_Custom_URL()?

Thanks much,
Ram

**Comment by LaurentGentzbittel** [comment]
dear Ram,
installing from the git repository fixed the problem. Thank you for that great resource.
Thanks !
Laurent
